package instructions

import "github.com/matjam/gandalf/internal/schema"

// The categories the shipped documents are filed under. They name defaults
// from the category set rather than a closed enum, since a vault may add to
// that set — but the documents Gandalf itself ships have fixed homes.
const (
	typeStandard schema.NoteType = "standard"
	typeReadme   schema.NoteType = "readme"
)

// docs is the shipped instruction set, in the order it is seeded. Order
// matters only for readability of seeding output; nothing depends on it.
//
// Related links are vault paths without the .md extension, and every one of
// them must resolve to another entry here — a seeded vault that fails its own
// linter would be an embarrassing first impression.
var docs = []Doc{
	{
		ID:       "operating",
		Source:   "content/gandalf/operating.md",
		Path:     "Gandalf/Operating.md",
		Title:    "Operating Contract",
		Type:     typeStandard,
		Delivery: AtBoot,
		Tags:     []string{"gandalf", "operating-contract"},
		Related: []string{
			"Gandalf/Memory",
			"Gandalf/Corrections",
		},
		When: "Always. Returned in full at session start.",
	},
	{
		ID:       "memory",
		Source:   "content/gandalf/memory.md",
		Path:     "Gandalf/Memory.md",
		Title:    "Memory Protocol",
		Type:     typeStandard,
		Delivery: AtBoot,
		Tags:     []string{"gandalf", "memory", "workflow"},
		Related: []string{
			"Gandalf/Operating",
		},
		When: "Always. Governs session notes, project notes, and note metadata.",
	},
	{
		ID:       "shipping",
		Source:   "content/gandalf/shipping.md",
		Path:     "Gandalf/Shipping.md",
		Title:    "Shipping",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"gandalf", "git", "ci", "shipping"},
		Related: []string{
			"Gandalf/Operating",
		},
		When: "Committing, branching, verifying, opening pull requests, releasing.",
	},
	{
		ID:       "diagnostics",
		Source:   "content/gandalf/diagnostics.md",
		Path:     "Gandalf/Diagnostics.md",
		Title:    "Diagnostics",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"gandalf", "diagnostics", "incidents"},
		Related: []string{
			"Gandalf/Operating",
		},
		When: "Bugs, failures, incidents, latency, anything behaving unexpectedly.",
	},
	{
		ID:       "external-content",
		Source:   "content/gandalf/external-content.md",
		Path:     "Gandalf/External Content.md",
		Title:    "External Content",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"gandalf", "external-content", "trackers"},
		Related: []string{
			"Gandalf/Operating",
		},
		When: "Issue trackers, wikis, shared documents, anything a human also edits.",
	},
	{
		ID:       "corrections",
		Source:   "content/gandalf/corrections.md",
		Path:     "Gandalf/Corrections.md",
		Title:    "Correction History",
		Type:     typeStandard,
		Delivery: Unlisted,
		Tags:     []string{"gandalf", "corrections"},
		Related: []string{
			"Gandalf/Operating",
		},
		When: "Reasoning behind a rule. Not an instruction source; not read at startup.",
	},

	{
		ID:       "architecture",
		Source:   "content/standards/architecture.md",
		Path:     "Standards/architecture.md",
		Title:    "Architecture",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "architecture"},
		Related:  []string{"Standards/README"},
		When:     "Service structure, boundaries, module layout, when to split something.",
	},
	{
		ID:       "code-quality",
		Source:   "content/standards/code-quality.md",
		Path:     "Standards/code-quality.md",
		Title:    "Code Quality",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "code-quality"},
		Related:  []string{"Standards/README"},
		When:     "File size, errors, tests, documentation, dead code, build artifacts.",
	},
	{
		ID:       "api-design",
		Source:   "content/standards/api-design.md",
		Path:     "Standards/api-design.md",
		Title:    "API Design",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "api-design"},
		Related:  []string{"Standards/README"},
		When:     "HTTP or RPC interfaces, status codes, pagination, compatibility.",
	},
	{
		ID:       "database",
		Source:   "content/standards/database.md",
		Path:     "Standards/database.md",
		Title:    "Database",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "database"},
		Related:  []string{"Standards/README"},
		When:     "Schema, queries, migrations, data access layers.",
	},
	{
		ID:       "security",
		Source:   "content/standards/security.md",
		Path:     "Standards/security.md",
		Title:    "Security",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "security"},
		Related:  []string{"Standards/README", "Standards/privacy"},
		When:     "Input validation, secrets, dependencies, auth, client bundles.",
	},
	{
		ID:       "observability",
		Source:   "content/standards/observability.md",
		Path:     "Standards/observability.md",
		Title:    "Observability",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "observability"},
		Related:  []string{"Standards/README"},
		When:     "Logging, tracing, metrics, and what a service must expose.",
	},
	{
		ID:       "privacy",
		Source:   "content/standards/privacy.md",
		Path:     "Standards/privacy.md",
		Title:    "Privacy",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "privacy"},
		Related:  []string{"Standards/README", "Gandalf/Operating"},
		When:     "Any design touching personal or sensitive data. See also the stop gate.",
	},
	{
		ID:       "language-go",
		Source:   "content/standards/language-go.md",
		Path:     "Standards/language-go.md",
		Title:    "Go",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "language-go"},
		Related:  []string{"Standards/README", "Standards/architecture"},
		When:     "Writing Go.",
	},
	{
		ID:       "language-python",
		Source:   "content/standards/language-python.md",
		Path:     "Standards/language-python.md",
		Title:    "Python",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "language-python"},
		Related:  []string{"Standards/README", "Standards/architecture"},
		When:     "Writing Python.",
	},
	{
		ID:       "language-typescript",
		Source:   "content/standards/language-typescript.md",
		Path:     "Standards/language-typescript.md",
		Title:    "TypeScript",
		Type:     typeStandard,
		Delivery: Listed,
		Tags:     []string{"standards", "language-typescript"},
		Related:  []string{"Standards/README", "Standards/architecture"},
		When:     "Writing TypeScript.",
	},

	{
		ID:       "readme-root",
		NoIndex:  true,
		Source:   "content/readme/root.md",
		Path:     "README.md",
		Title:    "Vault",
		Type:     typeReadme,
		Delivery: Unlisted,
		Tags:     []string{"vault", "folder-readme"},
		Related:  []string{"Gandalf/Operating"},
		When:     "Orientation for a human opening the vault.",
	},
	{
		ID:       "readme-sessions",
		NoIndex:  true,
		Source:   "content/readme/sessions.md",
		Path:     "Sessions/README.md",
		Title:    "Sessions",
		Type:     typeReadme,
		Delivery: Unlisted,
		Tags:     []string{"vault", "folder-readme", "sessions"},
		Related:  []string{"Gandalf/Memory"},
		When:     "What belongs in the sessions folder.",
	},
	{
		ID:       "readme-projects",
		NoIndex:  true,
		Source:   "content/readme/projects.md",
		Path:     "Projects/README.md",
		Title:    "Projects",
		Type:     typeReadme,
		Delivery: Unlisted,
		Tags:     []string{"vault", "folder-readme", "projects"},
		Related:  []string{"Gandalf/Memory"},
		When:     "What belongs in a project folder.",
	},
	{
		ID:       "readme-standards",
		NoIndex:  true,
		Source:   "content/readme/standards.md",
		Path:     "Standards/README.md",
		Title:    "Standards",
		Type:     typeReadme,
		Delivery: Unlisted,
		Tags:     []string{"vault", "folder-readme", "standards"},
		Related:  []string{"Gandalf/Operating"},
		When:     "What belongs in the standards folder, and that they are yours to change.",
	},
}
